### ISSUE TITLE
When you set a new wallpaper it's mixed English and Norwegian.

### ISSUE THREAD

**Issue by mikeey89** [miui-scandinavia/MA-XML-6.0-NORWEGIAN#12]
You can choose between "Avbryt" and "Apply" if I remember correctly.

**Comment by datagutt** [comment]
Still have some translating to do, will be done by fridays release.

**Comment by mikeey89** [comment]
Please let me know if you need help with translating. I have experience with translating computer systems and good aknowledge of Norwegian and I am from Norway.

**Comment by datagutt** [comment]
I'll let you know if i need any help

**Comment by datagutt** [comment]
Fixed.
