### ISSUE TITLE
gps status bar icon missing and gps problems + missed calls makes the phone unresponsive

### ISSUE THREAD

**Issue by Protx** [miui-scandinavia/MA-XML-6.0-NORWEGIAN#14]
MI4
Latest multi language rom 5.2.13. (and others before)
The problem is that gps status bar icon is missing and missed calls makes the phone unresponsive.
It is better described here: 
http://xiaomi.eu/community/threads/gps-issue.26574/

It is only like this when Norwegian Language is selected, if I use English Language it Works without the mentioned errors.

**Comment by ingbrzy** [comment]
update to 5.2.13

**Comment by cpasmoi** [comment]
maybe array issue with config_statusBarIcons in framework ?

**Comment by cpasmoi** [comment]
there are also a problem with arrays preferred_network_mode_choices in teleservices.apk,

**Comment by cpasmoi** [comment]
there are also some issues with mitab,

```
     <!-- Size mismatch! Translated: 23, Original: 13 -->
     <string-array name="preferred_network_mode_values">
     <!-- Size mismatch! Translated: 11, Original: 3 -->
     <string-array name="networkAttributes">
     <!-- Size mismatch! Translated: 4, Original: 3 -->
     <string-array name="pref_ua_choices">
     <!-- Size mismatch! Translated: 10, Original: 17 -->
     <string-array name="preferences_default_reminder_labels">
     <!-- Size mismatch! Translated: 10, Original: 16 -->
     <string-array name="reminder_minutes_labels">
     <!-- Size mismatch! Translated: 8, Original: 7 -->
     <string-array name="auto_silence_entries">
     <!-- Size mismatch! Translated: 8, Original: 7 -->
     <string-array name="auto_silence_values">
     <!-- Size mismatch! Translated: 11, Original: 3 -->
     <string-array name="networkAttributes">
```

**Comment by datagutt** [comment]
Hey,
I just pushed a fix and it will be in by next friday. Hopefully it will work, though i haven't tested it myself yet. I depend on others to report bug as i don't currently have a Xiaomi phone.

**Comment by Protx** [comment]
Hey.
I just tried Your latest commits, and both bugs I reported are fixed. Nice! 
:+1:
