### ISSUE TITLE
Norwegian language not included in MIUI weekly Multi 5.5.1?

### ISSUE THREAD

**Issue by Protx** [miui-scandinavia/MA-XML-6.0-NORWEGIAN#15]
Device: Xiaomi MI4

I have been using MIUI weekly rom the last months without issues. (Upgrading every week).
With Multi 5.5.1 I decided to to a fresh install, so I wiped everything. But while setting up, I could not choose Norwegian Language. (It is not there)
Tried With Multi 5.4.24 With the same result, no Norwegian Language.

I dont know but could it be excluded because of some errors in the repo!?:
http://translators.xiaomi.eu/XML_CHECK_FULL.html

Regards

**Comment by ingbrzy** [comment]
use MoreLocale2 for selecting Norwegian lang... Language selection in the settings will be fixed for next release.. thanks for the report..!

**Comment by Protx** [comment]
Thanks. :)

Den 02. mai 2015 10:45, skrev ingbrzy:

**Comment by datagutt** [comment]
Hey!
Nice to know my translation is being used. I was not aware of this issue. I am aware of the errors in the repo though, but they should not cause this to happen.
Thanks for the bug reports. Currently i am translating the strings for the last 3 weeks and i will also fix some of the errors (like this one)...
- Thomas
