### ISSUE TITLE
Google Play Services, Messaging FC when using Norwegian Language

### ISSUE THREAD

**Issue by karlemann** [miui-scandinavia/MA-XML-6.0-NORWEGIAN#17]
Using Norwegian locale (leo), Google Play Services and Messaging app are confirmed to FC on Weekly 5.8.6 and Stable 6.6.5 (EU).

For Google Play Services, this is when attempting to add Google Account.

EDIT: Seems to only occur on initial launch. Something to do with initial config files?

**Comment by karlemann** [comment]
Also confirmed to be the case when viewing appointment in Calendar app.

**Comment by datagutt** [comment]
Will look at this

**Comment by datagutt** [comment]
Hey,
Do you still have problems with this on MIUI 7?

**Comment by karlemann** [comment]
Hi, Multilanguage for LEO is not yet released, so haven't been able to
check.

2015-08-23 19:45 GMT+02:00 Thomas Lekanger notifications@github.com:

**Comment by karlemann** [comment]
Tried out 5.8.27, issues still there.

**Comment by ingbrzy** [comment]
fixed in v7 
https://github.com/miui-scandinavia/MA-XML-7.0-NORWEGIAN/commit/edd4ce349e632dd3f4323148b9a69c6288534925
